language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: osx
      osx_image: xcode9.4

before_install:
  - eval "${MATRIX_EVAL}"
script:
  - cmake .
  - make
